# ai/cdss/predictive_analytics.py
# Predictive Analytics Module — Phase 11
# Predicts clinical outcomes using rule-based scoring and ML heuristics.
#
# Models:
#   1. Disease Progression (trend analysis)
#   2. Readmission Risk (30-day)
#   3. Mortality Risk (severity scoring)
#   4. Emergency Prediction (90-day ER likelihood)
#   5. Treatment Success Prediction
#   6. Length of Stay Prediction
#
# Endpoint: POST /cdss/predictive-analytics

from flask import Blueprint, request, jsonify
import logging
import math
from datetime import datetime, timedelta

logger = logging.getLogger("cdss.predictive_analytics")

predictive_bp = Blueprint("predictive_analytics", __name__)


# ─────────────────────────────────────────────────────────────────────────────
# MAIN ROUTE
# ─────────────────────────────────────────────────────────────────────────────

@predictive_bp.route("/cdss/predictive-analytics", methods=["POST"])
def predictive_analytics():
    """
    Comprehensive Predictive Analytics Report.

    Request body:
    {
      "age": 65,
      "gender": "M",
      "conditions": ["heart_disease", "diabetes", "hypertension"],
      "medications": ["metformin", "lisinopril", "atorvastatin"],
      "vitals": { "systolic_bp": 150, "bmi": 29, "cholesterol": 220 },
      "labs": { "hba1c": 7.8, "creatinine": 1.4, "egfr": 55 },
      "recentHospitalizations": 1,
      "adherenceScore": 75,
      "smokingStatus": true,
      "alcoholUse": false,
      "exerciseFrequency": "low",
      "socialSupport": "moderate",
      "recentRecords": []
    }
    """
    try:
        data = request.get_json(silent=True) or {}
        logger.info(f"Predictive analytics request for age={data.get('age')}")

        age            = int(data.get("age", 45))
        gender         = str(data.get("gender", "M")).upper()
        conditions     = [str(c).lower() for c in data.get("conditions", [])]
        medications    = [str(m).lower() for m in data.get("medications", [])]
        vitals         = data.get("vitals", {})
        labs           = data.get("labs", {})
        recent_hosp    = int(data.get("recentHospitalizations", 0))
        adherence_score = int(data.get("adherenceScore", 80))
        smoking        = bool(data.get("smokingStatus", False))
        alcohol        = bool(data.get("alcoholUse", False))
        exercise       = str(data.get("exerciseFrequency", "moderate")).lower()
        social_support = str(data.get("socialSupport", "moderate")).lower()
        recent_records = data.get("recentRecords", [])

        ctx = dict(
            age=age, gender=gender, conditions=conditions, medications=medications,
            vitals=vitals, labs=labs, recent_hosp=recent_hosp,
            adherence_score=adherence_score, smoking=smoking, alcohol=alcohol,
            exercise=exercise, social_support=social_support,
        )

        # ── Run all prediction models ──────────────────────────────────────
        readmission  = _predict_readmission(ctx)
        mortality    = _predict_mortality(ctx)
        emergency    = _predict_emergency(ctx)
        treatment    = _predict_treatment_success(ctx)
        los          = _predict_length_of_stay(ctx)
        progression  = _predict_disease_progression(ctx)

        report = {
            "timestamp":      datetime.utcnow().isoformat() + "Z",
            "predictions": {
                "readmission30Day":   readmission,
                "mortalityRisk":      mortality,
                "emergencyRisk90Day": emergency,
                "treatmentSuccess":   treatment,
                "expectedLOS":        los,
                "diseaseProgression": progression,
            },
            "riskStratification":  _stratify_risk(readmission, mortality, emergency),
            "actionableInsights":  _generate_insights(ctx, readmission, mortality, emergency),
            "trendData":           _generate_trend_data(ctx),
            "disclaimer": (
                "Predictive analytics are generated by an AI system using rule-based "
                "and statistical models. Results are probabilistic estimates for clinical "
                "decision support only — NOT definitive diagnoses or prognoses. "
                "All clinical decisions must be made by qualified medical professionals."
            ),
        }

        logger.info(f"Predictive analytics completed — readmission: {readmission['probability']}%")
        return jsonify(report), 200

    except Exception as e:
        logger.error(f"Predictive analytics error: {e}")
        return jsonify({"error": "Predictive analytics error", "details": str(e)}), 500


# ─────────────────────────────────────────────────────────────────────────────
# PREDICTION MODELS
# ─────────────────────────────────────────────────────────────────────────────

def _predict_readmission(ctx):
    """
    30-day Hospital Readmission Risk.
    Based on HOSPITAL score + additional factors.
    """
    score = 0
    factors = []

    # HOSPITAL score components
    if float(ctx["labs"].get("sodium", 140)) < 135:
        score += 2; factors.append("Low sodium (hyponatremia)")
    if ctx["recent_hosp"] >= 1:
        score += 2 * min(ctx["recent_hosp"], 3)
        factors.append(f"Prior hospitalization(s): {ctx['recent_hosp']}")
    if ctx["adherence_score"] < 60:
        score += 2; factors.append("Low medication adherence")
    if len(ctx["conditions"]) >= 3:
        score += 2; factors.append(f"Multiple comorbidities ({len(ctx['conditions'])})")
    if ctx["age"] > 75:
        score += 2; factors.append("Advanced age (> 75)")
    elif ctx["age"] > 65:
        score += 1; factors.append("Older age (> 65)")
    if ctx["exercise"] == "low":
        score += 1; factors.append("Low physical activity")
    if ctx["social_support"] == "low":
        score += 2; factors.append("Inadequate social support")
    if float(ctx["labs"].get("egfr", 90)) < 45:
        score += 2; factors.append("Reduced kidney function (eGFR < 45)")
    if "heart_disease" in ctx["conditions"] or "heart failure" in ctx["conditions"]:
        score += 2; factors.append("Heart disease / Heart failure")

    prob = _score_to_probability(score, max_score=20)
    level = "HIGH" if prob >= 60 else "MODERATE" if prob >= 35 else "LOW"

    return {
        "probability": round(prob, 1),
        "level":       level,
        "score":       score,
        "factors":     factors,
        "description": f"Estimated {round(prob, 1)}% probability of hospital readmission within 30 days.",
        "riskWindow":  "30 days",
        "modifiable":  _modifiable_factors(factors),
    }


def _predict_mortality(ctx):
    """
    In-hospital / short-term mortality risk using modified APACHE-II-style scoring.
    """
    score = 0
    factors = []

    if ctx["age"] > 75: score += 6; factors.append("Advanced age > 75")
    elif ctx["age"] > 65: score += 4; factors.append("Age > 65")
    elif ctx["age"] > 55: score += 2

    sbp = float(ctx["vitals"].get("systolic_bp", 120))
    if sbp > 180: score += 4; factors.append("Severe hypertension (BP > 180)")
    elif sbp < 90: score += 6; factors.append("Hypotension (BP < 90) — critical")

    for cond in ctx["conditions"]:
        if "cancer" in cond:       score += 5; factors.append("Active malignancy")
        if "heart failure" in cond: score += 4; factors.append("Heart failure")
        if "liver" in cond and "disease" in cond: score += 3; factors.append("Liver disease")
        if "kidney" in cond:       score += 3; factors.append("Kidney disease")

    if ctx["recent_hosp"] >= 2: score += 2; factors.append("Multiple recent hospitalizations")
    if ctx["smoking"]: score += 1; factors.append("Smoking")
    if len(ctx["conditions"]) >= 4: score += 2; factors.append("High comorbidity burden")

    prob = _score_to_probability(score, max_score=30)
    level = "CRITICAL" if prob >= 60 else "HIGH" if prob >= 35 else "MODERATE" if prob >= 15 else "LOW"

    return {
        "probability": round(prob, 1),
        "level":       level,
        "score":       score,
        "factors":     factors,
        "description": f"Estimated {round(prob, 1)}% short-term mortality risk based on clinical parameters.",
        "riskWindow":  "In-hospital / 90-day",
    }


def _predict_emergency(ctx):
    """
    90-day Emergency Department Visit Prediction.
    """
    score = 0
    factors = []

    if ctx["recent_hosp"] >= 1:
        score += 3 * min(ctx["recent_hosp"], 3)
        factors.append("Recent hospitalization")
    if ctx["adherence_score"] < 70:
        score += 3; factors.append("Low medication adherence")
    if len(ctx["conditions"]) >= 3:
        score += 2; factors.append("Multiple chronic conditions")
    if "heart_disease" in ctx["conditions"]:
        score += 3; factors.append("Cardiac disease")
    if "diabetes" in ctx["conditions"] and float(ctx["labs"].get("hba1c", 7)) > 9:
        score += 3; factors.append("Poorly controlled diabetes (HbA1c > 9)")
    if ctx["social_support"] == "low":
        score += 2; factors.append("Low social support")
    if ctx["exercise"] == "low":
        score += 1; factors.append("Physical inactivity")
    if ctx["age"] > 70:
        score += 2; factors.append("Age > 70")

    prob = _score_to_probability(score, max_score=25)
    level = "HIGH" if prob >= 60 else "MODERATE" if prob >= 35 else "LOW"

    return {
        "probability": round(prob, 1),
        "level":       level,
        "score":       score,
        "factors":     factors,
        "description": f"Estimated {round(prob, 1)}% probability of unplanned ER visit within 90 days.",
        "riskWindow":  "90 days",
        "modifiable":  _modifiable_factors(factors),
    }


def _predict_treatment_success(ctx):
    """
    Treatment Success Probability — adherence × disease factors.
    """
    base_prob = ctx["adherence_score"]  # Start with adherence score

    # Complexity penalty
    base_prob -= len(ctx["conditions"]) * 3
    base_prob -= len(ctx["medications"]) * 1.5

    # Lifestyle bonuses
    if ctx["exercise"] == "high": base_prob += 8
    elif ctx["exercise"] == "moderate": base_prob += 4
    if not ctx["smoking"]: base_prob += 5
    if not ctx["alcohol"]: base_prob += 3
    if ctx["social_support"] == "high": base_prob += 7
    elif ctx["social_support"] == "moderate": base_prob += 3

    # Age adjustment
    if ctx["age"] > 75: base_prob -= 8
    elif ctx["age"] > 65: base_prob -= 4

    prob = max(15, min(95, base_prob))
    level = "HIGH" if prob >= 70 else "MODERATE" if prob >= 50 else "LOW"

    return {
        "probability": round(prob, 1),
        "level":       level,
        "description": f"Estimated {round(prob, 1)}% probability of successful treatment outcome.",
        "keyFactors":  {
            "adherence":     f"{ctx['adherence_score']}%",
            "exercise":      ctx["exercise"],
            "socialSupport": ctx["social_support"],
            "conditions":    len(ctx["conditions"]),
        },
        "improvementAreas": _treatment_improvements(ctx),
    }


def _predict_length_of_stay(ctx):
    """
    Expected hospital length of stay (days) if admitted.
    """
    base_los = 3.0  # baseline days

    # Condition complexity
    base_los += len(ctx["conditions"]) * 0.8

    # Age
    if ctx["age"] > 75: base_los += 3
    elif ctx["age"] > 65: base_los += 1.5

    # Specific high-complexity conditions
    for cond in ctx["conditions"]:
        if "heart failure" in cond: base_los += 3
        if "kidney" in cond: base_los += 2
        if "liver" in cond: base_los += 2
        if "stroke" in cond: base_los += 5
        if "cancer" in cond: base_los += 4

    # ICU likelihood
    sbp = float(ctx["vitals"].get("systolic_bp", 120))
    icu_likely = sbp < 90 or sbp > 190 or len(ctx["conditions"]) >= 4

    if icu_likely: base_los += 3

    return {
        "estimatedDays":  round(base_los, 1),
        "icuLikely":      icu_likely,
        "range":          {"min": max(1, round(base_los * 0.7)), "max": round(base_los * 1.5)},
        "description":    f"If admitted, estimated stay of {round(base_los, 1)} days (range: {max(1, round(base_los * 0.7))}–{round(base_los * 1.5)} days).",
        "complexity":     "HIGH" if base_los > 8 else "MODERATE" if base_los > 5 else "LOW",
    }


def _predict_disease_progression(ctx):
    """
    Disease progression trend for primary conditions.
    """
    progressions = []

    for cond in ctx["conditions"][:3]:
        adherence = ctx["adherence_score"]
        exercise  = ctx["exercise"]
        smoking   = ctx["smoking"]

        controlled = adherence >= 70 and exercise != "low" and not smoking
        progression_rate = "Stable" if controlled else "Progressive"

        risk = "LOW" if controlled else "MODERATE"
        if not controlled and len(ctx["conditions"]) >= 3:
            risk = "HIGH"

        timeline = []
        base_risk = 100 - adherence
        for month in [1, 3, 6, 12]:
            # Simulate risk increase if uncontrolled
            m_risk = base_risk + (0 if controlled else month * 1.5)
            m_risk = min(95, max(5, m_risk))
            timeline.append({"month": month, "risk": round(m_risk, 1)})

        progressions.append({
            "condition":       cond.replace("_", " ").title(),
            "progression":     progression_rate,
            "risk":            risk,
            "controlled":      controlled,
            "timeline":        timeline,
            "recommendation":  "Maintain current management" if controlled else "Review with specialist — condition may worsen without intervention",
        })

    return progressions


# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def _score_to_probability(score, max_score=20):
    """Map a raw score to a 0–95% probability using a logistic-like curve."""
    normalized = min(1.0, score / max_score)
    # Logistic transform
    prob = 1 / (1 + math.exp(-8 * (normalized - 0.5)))
    return max(2, min(95, round(prob * 100, 1)))


def _modifiable_factors(factors):
    """Filter factors that are modifiable."""
    modifiable_keywords = [
        "adherence", "activity", "exercise", "smoking", "alcohol", "support", "diet"
    ]
    return [f for f in factors if any(kw in f.lower() for kw in modifiable_keywords)]


def _treatment_improvements(ctx):
    improvements = []
    if ctx["adherence_score"] < 80:
        improvements.append("Improve medication adherence (use pill organizers, reminders)")
    if ctx["exercise"] == "low":
        improvements.append("Increase physical activity — even 30 min/day of walking is beneficial")
    if ctx["smoking"]:
        improvements.append("Smoking cessation — single most impactful lifestyle change")
    if ctx["alcohol"]:
        improvements.append("Reduce alcohol consumption")
    if ctx["social_support"] != "high":
        improvements.append("Strengthen social support network (family, community groups)")
    return improvements


def _stratify_risk(readmission, mortality, emergency):
    scores = [readmission["probability"], mortality["probability"], emergency["probability"]]
    avg = sum(scores) / len(scores)
    overall = "CRITICAL" if avg >= 65 else "HIGH" if avg >= 45 else "MODERATE" if avg >= 25 else "LOW"

    return {
        "overall":          overall,
        "averageRisk":      round(avg, 1),
        "riskComponents": {
            "readmission":  readmission["level"],
            "mortality":    mortality["level"],
            "emergency":    emergency["level"],
        },
        "priorityAction": (
            "⚠️ Immediate medical review recommended" if overall == "CRITICAL"
            else "Schedule urgent specialist appointment" if overall == "HIGH"
            else "Schedule routine follow-up within 1–3 months" if overall == "MODERATE"
            else "Continue current management with regular monitoring"
        ),
    }


def _generate_insights(ctx, readmission, mortality, emergency):
    insights = []

    if readmission["probability"] > 50:
        insights.append({
            "type":    "warning",
            "title":   "High Readmission Risk",
            "message": "Consider enhanced discharge planning and follow-up scheduling.",
            "action":  "Schedule follow-up within 7 days of any hospital discharge",
        })

    if ctx["adherence_score"] < 70:
        insights.append({
            "type":    "action",
            "title":   "Low Medication Adherence",
            "message": f"Adherence score: {ctx['adherence_score']}%. Poor adherence increases all risk categories.",
            "action":  "Consider pill organizers, phone reminders, or pharmacist counseling",
        })

    if ctx["social_support"] == "low":
        insights.append({
            "type":    "info",
            "title":   "Limited Social Support",
            "message": "Patients with stronger social networks have significantly better outcomes.",
            "action":  "Connect with community health workers or support groups",
        })

    if ctx["smoking"]:
        insights.append({
            "type":    "action",
            "title":   "Smoking Cessation",
            "message": "Smoking is a major independent risk factor. Cessation within 1 year reduces cardiovascular risk by up to 50%.",
            "action":  "Enroll in a smoking cessation program — ask your doctor about Nicotine Replacement Therapy (NRT)",
        })

    if emergency["probability"] > 50:
        insights.append({
            "type":    "warning",
            "title":   "Elevated ER Risk",
            "message": f"{emergency['probability']}% likelihood of ER visit within 90 days.",
            "action":  "Establish clear care plan and emergency action plan with your physician",
        })

    if not insights:
        insights.append({
            "type":    "success",
            "title":   "Manageable Risk Profile",
            "message": "Your current risk profile is manageable with continued adherence to your treatment plan.",
            "action":  "Continue regular monitoring and maintain healthy lifestyle habits",
        })

    return insights


def _generate_trend_data(ctx):
    """Generate simulated trend data for visualization (12 months)."""
    adherence = ctx["adherence_score"]
    base      = 100 - adherence
    trend     = []

    for month in range(1, 13):
        # Controlled improvement or worsening trend
        delta = -0.5 if adherence >= 75 else 0.8
        val   = max(5, min(95, base + delta * month + (month % 3) * 0.5))
        trend.append({
            "month":     month,
            "label":     f"Month {month}",
            "riskScore": round(val, 1),
        })

    return {
        "riskTrend":  trend,
        "baseline":   base,
        "projection": "Improving" if adherence >= 75 else "Worsening without intervention",
    }
