// frontend/src/utils/web3.js
// ethers.js v6 helpers — MetaMask connection, contract access, utility functions
//
// NOTE: MediChain.json is auto-generated by:
//   npx hardhat run blockchain/scripts/deploy.js --network localhost
// It is exported to frontend/src/contracts/MediChain.json by the deploy script.

import { ethers } from 'ethers';

// Gracefully handle missing contract artifact (before first deploy)
let MediChainABI = { abi: [], address: '' };
try {
  MediChainABI = require('../contracts/MediChain.json');
} catch {
  console.warn('[web3] MediChain.json not found — run the deploy script first.');
}

// ── connectWallet ─────────────────────────────────────────────────────────────
/**
 * Requests MetaMask account access and returns provider, signer, address, chainId.
 * @returns {{ provider, signer, address: string, chainId: bigint }}
 */
export const connectWallet = async () => {
  if (!window.ethereum) {
    throw new Error('Please install MetaMask to use MediChain.');
  }

  // Trigger MetaMask popup
  await window.ethereum.request({ method: 'eth_requestAccounts' });

  const provider = new ethers.BrowserProvider(window.ethereum);
  const signer   = await provider.getSigner();
  const address  = await signer.getAddress();
  const { chainId } = await provider.getNetwork();

  return { provider, signer, address, chainId };
};

// ── getContract ───────────────────────────────────────────────────────────────
/**
 * Returns a writable MediChain contract instance connected to the given signer.
 * @param {ethers.Signer} signer
 */
export const getContract = (signer) => {
  if (!MediChainABI.address) {
    throw new Error('Contract address not found. Deploy the smart contract first.');
  }
  return new ethers.Contract(MediChainABI.address, MediChainABI.abi, signer);
};

// ── getReadonlyContract ───────────────────────────────────────────────────────
/**
 * Returns a read-only contract instance using a JsonRpcProvider (no MetaMask needed).
 */
export const getReadonlyContract = () => {
  const provider = new ethers.JsonRpcProvider(
    process.env.REACT_APP_RPC_URL || 'http://127.0.0.1:8545'
  );
  return new ethers.Contract(MediChainABI.address, MediChainABI.abi, provider);
};

// ── switchToHardhat ───────────────────────────────────────────────────────────
/**
 * Asks MetaMask to switch to the local Hardhat network (chainId 31337).
 * If the network is not yet added, it adds it automatically.
 */
export const switchToHardhat = async () => {
  if (!window.ethereum) throw new Error('MetaMask is not installed.');

  const HARDHAT_CHAIN_ID = '0x7A69'; // 31337 in hex

  try {
    await window.ethereum.request({
      method: 'wallet_switchEthereumChain',
      params: [{ chainId: HARDHAT_CHAIN_ID }],
    });
  } catch (switchError) {
    // Error code 4902: the network has not been added to MetaMask yet
    if (switchError.code === 4902) {
      await window.ethereum.request({
        method: 'wallet_addEthereumChain',
        params: [
          {
            chainId:         HARDHAT_CHAIN_ID,
            chainName:       'Hardhat Local',
            nativeCurrency:  { name: 'ETH', symbol: 'ETH', decimals: 18 },
            rpcUrls:         ['http://127.0.0.1:8545'],
            blockExplorerUrls: [],
          },
        ],
      });
    } else {
      throw switchError;
    }
  }
};

// ── Utility Functions ─────────────────────────────────────────────────────────

/**
 * Shortens an Ethereum address for display: 0x1234...abcd
 * @param {string} addr
 */
export const formatAddress = (addr) =>
  addr ? `${addr.slice(0, 6)}...${addr.slice(-4)}` : '';

/**
 * Validates an Ethereum address using ethers.js
 * @param {string} addr
 */
export const isValidEthAddress = (addr) => ethers.isAddress(addr);

/**
 * Converts a date string or Date object to a Unix timestamp (seconds)
 * @param {string|Date} date
 */
export const toUnixTimestamp = (date) =>
  Math.floor(new Date(date).getTime() / 1000);

/**
 * Listens for MetaMask account and network change events.
 * @param {{ onAccountChange: Function, onNetworkChange: Function }}
 */
export const listenToWalletEvents = ({ onAccountChange, onNetworkChange } = {}) => {
  if (!window.ethereum) return;
  if (onAccountChange) {
    window.ethereum.on('accountsChanged', (accounts) => onAccountChange(accounts[0] || null));
  }
  if (onNetworkChange) {
    window.ethereum.on('chainChanged', (chainId) => onNetworkChange(chainId));
  }
};

// ── MediChain Contract Wrappers (used by hooks) ────────────────────────────────

/**
 * Normalizes UI record types to contract-enforced values.
 * Contract allows: prescription | lab_report | diagnosis | xray | other
 * @param {string} recordType
 */
export const normalizeRecordType = (recordType) => {
  const t = (recordType || '').trim().toLowerCase();
  if (t === 'lab-report' || t === 'lab_report') return 'lab_report';
  if (t === 'xray' || t === 'imaging') return 'xray';
  if (t === 'diagnosis') return 'diagnosis';
  if (t === 'prescription') return 'prescription';
  return 'other';
};

/**
 * Builds a gateway URL from a CID (Pinata default).
 * @param {string} cid
 */
export const cidToGatewayUrl = (cid) => `https://gateway.pinata.cloud/ipfs/${cid}`;

/**
 * Registers the connected wallet as a patient on-chain.
 * @returns {Promise<ethers.TransactionResponse>}
 */
export const registerPatientOnChain = async () => {
  const { signer } = await connectWallet();
  const contract = getContract(signer);
  return await contract.registerPatient();
};

/**
 * Grants doctor access for the connected patient wallet.
 * @param {string} doctorAddress
 * @returns {Promise<ethers.TransactionResponse>}
 */
export const grantAccessOnChain = async (doctorAddress) => {
  const { signer } = await connectWallet();
  const contract = getContract(signer);
  return await contract.grantDoctorAccess(doctorAddress);
};

/**
 * Revokes doctor access for the connected patient wallet.
 * @param {string} doctorAddress
 * @returns {Promise<ethers.TransactionResponse>}
 */
export const revokeAccessOnChain = async (doctorAddress) => {
  const { signer } = await connectWallet();
  const contract = getContract(signer);
  return await contract.revokeDoctorAccess(doctorAddress);
};

/**
 * Checks whether doctorAddress has access to patientAddress.
 * @param {string} patientAddress
 * @param {string} doctorAddress
 */
export const checkAccessOnChain = async (patientAddress, doctorAddress) => {
  const contract = getReadonlyContract();
  return await contract.hasAccess(patientAddress, doctorAddress);
};

/**
 * Adds a medical record for a patient (caller must be patient or authorised doctor).
 * @param {string} patientAddress
 * @param {string} ipfsCID
 * @param {string} ipfsURL
 * @param {string} recordType
 * @param {string} notes
 * @returns {Promise<ethers.TransactionResponse>}
 */
export const addRecordOnChain = async (patientAddress, ipfsCID, ipfsURL, recordType, notes) => {
  const { signer } = await connectWallet();
  const contract = getContract(signer);
  const normalizedType = normalizeRecordType(recordType);
  return await contract.addMedicalRecord(patientAddress, ipfsCID, ipfsURL, normalizedType, notes || '');
};

/**
 * Gets records for a patient (caller must be patient or authorised doctor).
 * Uses connected wallet because the contract checks msg.sender.
 * @param {string} patientAddress
 */
export const getRecordsFromChain = async (patientAddress) => {
  const { signer } = await connectWallet();
  const contract = getContract(signer);
  return await contract.getMedicalRecords(patientAddress);
};
